/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:3d8bf836-6501-4a27-b802-b13a43a5f1ec",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_BPwzPFNWe",
    "aws_user_pools_web_client_id": "77p8psrb5ckas495qiaqtec126",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://d2h2qvb2tjdpbejzazl2d46wem.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-zo2ekbzynncdhjfqs4fb3eysbq",
    "aws_user_files_s3_bucket": "compassfrontenda511dfb8b7244c2f9b761b3e116e2083155547-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
